## Note: mode1-taxi, mode2-FHV, mode3-shared FHV, mode4-PT, mode5-walking

In [10]:
import numpy as np
import pandas as pd
import warnings
from tqdm import tqdm
warnings.filterwarnings("ignore")

## Data

In [5]:
acs = pd.read_csv('final_acs_transportation_choice.csv')#, index_col=0)
acs.head()

   taxi_zone   P(mode1)    P(mode2)   P(mode3)      P(mode4)     P(mode5)
0        3.0   0.526074   81.318503  33.425463   7948.271384   915.458576
1        4.0  32.888450  108.134955  64.938615   7212.769464  3373.268515
2        5.0   0.245777   39.742128   6.404244   8270.173881   114.433969
3        6.0   0.453222   31.753306   7.808959   4919.798684   480.185830
4        7.0  27.457307  153.425489  40.431632  34826.940798  2987.744775

In [6]:
mode_data = pd.read_csv('final_allMode_with_wage.csv', index_col=0).set_index('ODpair')
mode_data = mode_data.dropna()
mode_data.head()

,PUlocationID,DOlocationID,duration,price,2500,7500,12500,17500,22500,30000,42500,62500,87500,125000,225000,mode,nest
ODpair,,,,,,,,,,,,,,,,,
3-3,3,3,6.508943,16.647073,11.412271,16.389811,29.504545,12.840609,18.871367,26.936423,30.543336,42.705845,26.705581,33.702991,23.387221,1,1
3-4,3,4,39.695000,64.000000,0.250819,0.360216,0.648452,0.282211,0.414755,0.592009,0.671282,0.938590,0.586936,0.740725,0.514005,2,1
3-4,3,4,45.216667,61.500000,0.250819,0.360216,0.648452,0.282211,0.414755,0.592009,0.671282,0.938590,0.586936,0.740725,0.514005,3,1
3-4,3,4,83.000000,5.500000,0.250819,0.360216,0.648452,0.282211,0.414755,0.592009,0.671282,0.938590,0.586936,0.740725,0.514005,4,2
3-4,3,4,225.933333,0.000000,0.250819,0.360216,0.648452,0.282211,0.414755,0.592009,0.671282,0.938590,0.586936,0.740725,0.514005,5,3

In [27]:
acs[:7]

   taxi_zone   P(mode1)    P(mode2)   P(mode3)      P(mode4)     P(mode5)
0          3   0.526074   81.318503  33.425463   7948.271384   915.458576
1          4  32.888450  108.134955  64.938615   7212.769464  3373.268515
2          5   0.245777   39.742128   6.404244   8270.173881   114.433969
3          6   0.453222   31.753306   7.808959   4919.798684   480.185830
4          7  27.457307  153.425489  40.431632  34826.940798  2987.744775
5          9   0.051277    8.292491   2.345830   6118.013650   397.296751
6         10   8.828095  113.555345  48.233656  10257.551077   647.831828

In [26]:
mode_data[:7242]

,PUlocationID,DOlocationID,duration,price,2500,7500,12500,17500,22500,30000,42500,62500,87500,125000,225000,mode,nest
ODpair,,,,,,,,,,,,,,,,,
3-3,3,3,6.508943,16.647073,11.412271,16.389811,29.504545,12.840609,18.871367,26.936423,30.543336,42.705845,26.705581,33.702991,23.387221,1,1
3-4,3,4,39.695000,64.000000,0.250819,0.360216,0.648452,0.282211,0.414755,0.592009,0.671282,0.938590,0.586936,0.740725,0.514005,2,1
3-4,3,4,45.216667,61.500000,0.250819,0.360216,0.648452,0.282211,0.414755,0.592009,0.671282,0.938590,0.586936,0.740725,0.514005,3,1
3-4,3,4,83.000000,5.500000,0.250819,0.360216,0.648452,0.282211,0.414755,0.592009,0.671282,0.938590,0.586936,0.740725,0.514005,4,2
3-4,3,4,225.933333,0.000000,0.250819,0.360216,0.648452,0.282211,0.414755,0.592009,0.671282,0.938590,0.586936,0.740725,0.514005,5,3
3-7,3,7,47.880952,43.157143,1.504915,2.161294,3.890709,1.693267,2.488532,3.552056,4.027693,5.631540,3.521615,4.444350,3.084029,1,1
3-7,3,7,30.521739,47.000000,1.504915,2.161294,3.890709,1.693267,2.488532,3.552056,4.027693,5.631540,3.521615,4.444350,3.084029,2,1
3-7,3,7,37.159009,45.000000,1.504915,2.161294,3.890709,1.693267,2.488532,3.552056,4.027693,5.631540,3.521615,4.444350,3.084029,3,1
3-7,3,7,69.000000,5.500000,1.504915,2.161294,3.890709,1.693267,2.488532,3.552056,4.027693,5.631540,3.521615,4.444350,3.084029,4,2
3-7,3,7,231.366667,0.000000,1.504915,2.161294,3.890709,1.693267,2.488532,3.552056,4.027693,5.631540,3.521615,4.444350,3.084029,5,3
3-9,3,9,19.547126,39.000000,0.083606,0.120072,0.216151,0.094070,0.138252,0.197336,0.223761,0.312863,0.195645,0.246908,0.171335,2,1
3-9,3,9,31.300000,38.000000,0.083606,0.120072,0.216151,0.094070,0.138252,0.197336,0.223761,0.312863,0.195645,0.246908,0.171335,3,1
3-9,3,9,74.000000,8.250000,0.083606,0.120072,0.216151,0.094070,0.138252,0.197336,0.223761,0.312863,0.195645,0.246908,0.171335,4,2
3-9,3,9,422.916667,0.000000,0.083606,0.120072,0.216151,0.094070,0.138252,0.197336,0.223761,0.312863,0.195645,0.246908,0.171335,5,3
3-10,3,10,28.500000,69.500000,0.125410,0.180108,0.324226,0.141106,0.207378,0.296005,0.335641,0.469295,0.293468,0.370363,0.257002,2,1
3-10,3,10,69.550000,66.500000,0.125410,0.180108,0.324226,0.141106,0.207378,0.296005,0.335641,0.469295,0.293468,0.370363,0.257002,3,1
3-10,3,10,107.000000,11.000000,0.125410,0.180108,0.324226,0.141106,0.207378,0.296005,0.335641,0.469295,0.293468,0.370363,0.257002,4,2
3-10,3,10,477.050000,0.000000,0.125410,0.180108,0.324226,0.141106,0.207378,0.296005,0.335641,0.469295,0.293468,0.370363,0.257002,5,3
3-11,3,11,98.925000,91.000000,0.167213,0.240144,0.432301,0.188141,0.276504,0.394673,0.447521,0.625727,0.391291,0.493817,0.342670,2,1
3-11,3,11,106.000000,5.500000,0.167213,0.240144,0.432301,0.188141,0.276504,0.394673,0.447521,0.625727,0.391291,0.493817,0.342670,4,2
3-11,3,11,316.416667,0.000000,0.167213,0.240144,0.432301,0.188141,0.276504,0.394673,0.447521,0.625727,0.391291,0.493817,0.342670,5,3
3-13,3,13,54.867754,69.500000,0.543441,0.780467,1.404978,0.611458,0.898637,1.282687,1.454445,2.033612,1.271694,1.604904,1.113677,2,1
3-13,3,13,38.500000,66.500000,0.543441,0.780467,1.404978,0.611458,0.898637,1.282687,1.454445,2.033612,1.271694,1.604904,1.113677,3,1
3-13,3,13,81.000000,2.750000,0.543441,0.780467,1.404978,0.611458,0.898637,1.282687,1.454445,2.033612,1.271694,1.604904,1.113677,4,2
3-13,3,13,222.000000,0.000000,0.543441,0.780467,1.404978,0.611458,0.898637,1.282687,1.454445,2.033612,1.271694,1.604904,1.113677,5,3
3-14,3,14,58.197917,85.000000,0.459835,0.660395,1.188828,0.517387,0.760385,1.085350,1.230684,1.720748,1.076049,1.357996,0.942342,2,1
3-14,3,14,79.783333,81.000000,0.459835,0.660395,1.188828,0.517387,0.760385,1.085350,1.230684,1.720748,1.076049,1.357996,0.942342,3,1
3-14,3,14,104.000000,8.250000,0.459835,0.660395,1.188828,0.517387,0.760385,1.085350,1.230684,1.720748,1.076049,1.357996,0.942342,4,2
3-14,3,14,261.183333,0.000000,0.459835,0.660395,1.188828,0.517387,0.760385,1.085350,1.230684,1.720748,1.076049,1.357996,0.942342,5,3
3-15,3,15,20.229487,37.500000,0.836064,1.200719,2.161505,0.940704,1.382518,1.973364,2.237607,3.128633,1.956453,2.469084,1.713350,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10-257,10,257,146.550000,0.000000,0.099936,0.103888,0.138740,0.117747,0.094238,0.187861,0.275889,0.315668,0.222097,0.246118,0.197819,5,3
10-258,10,258,17.358333,16.035714,4.097369,4.259412,5.688336,4.827615,3.863775,7.702297,11.311433,12.942384,9.105967,10.090851,8.110561,1,1
10-258,10,258,16.553735,18.000000,4.097369,4.259412,5.688336,4.827615,3.863775,7.702297,11.311433,12.942384,9.105967,10.090851,8.110561,2,1
10-258,10,258,20.907300,18.000000,4.097369,4.259412,5.688336,4.827615,3.863775,7.702297,11.311433,12.942384,9.105967,10.090851,8.110561,3,1
10-258,10,258,42.000000,5.500000,4.097369,4.259412,5.688336,4.827615,3.863775,7.702297,11.311433,12.942384,9.105967,10.090851,8.110561,4,2
10-258,10,258,130.016667,0.000000,4.097369,4.259412,5.688336,4.827615,3.863775,7.702297,11.311433,12.942384,9.105967,10.090851,8.110561,5,3
10-259,10,259,35.434444,55.500000,0.299808,0.311664,0.416220,0.353240,0.282715,0.563583,0.827666,0.947004,0.666290,0.738355,0.593456,2,1
10-259,10,259,46.800000,53.000000,0.299808,0.311664,0.416220,0.353240,0.282715,0.563583,0.827666,0.947004,0.666290,0.738355,0.593456,3,1
10-259,10,259,118.000000,8.250000,0.299808,0.311664,0.416220,0.353240,0.282715,0.563583,0.827666,0.947004,0.666290,0.738355,0.593456,4,2
10-259,10,259,180.283333,0.000000,0.299808,0.311664,0.416220,0.353240,0.282715,0.563583,0.827666,0.947004,0.666290,0.738355,0.593456,5,3
10-260,10,260,25.897222,32.166667,4.397177,4.571077,6.104555,5.180855,4.146490,8.265880,12.139099,13.889388,9.772257,10.829206,8.704016,1,1
10-260,10,260,27.577588,32.500000,4.397177,4.571077,6.104555,5.180855,4.146490,8.265880,12.139099,13.889388,9.772257,10.829206,8.704016,2,1
10-260,10,260,36.817606,31.000000,4.397177,4.571077,6.104555,5.180855,4.146490,8.265880,12.139099,13.889388,9.772257,10.829206,8.704016,3,1
10-260,10,260,51.000000,8.250000,4.397177,4.571077,6.104555,5.180855,4.146490,8.265880,12.139099,13.889388,9.772257,10.829206,8.704016,4,2
10-260,10,260,151.683333,0.000000,4.397177,4.571077,6.104555,5.180855,4.146490,8.265880,12.139099,13.889388,9.772257,10.829206,8.704016,5,3
10-261,10,261,55.817150,52.050000,2.098653,2.181650,2.913538,2.472681,1.979007,3.945079,5.793661,6.629026,4.664032,5.168485,4.154190,1,1
10-261,10,261,54.598667,49.500000,2.098653,2.181650,2.913538,2.472681,1.979007,3.945079,5.793661,6.629026,4.664032,5.168485,4.154190,2,1
10-261,10,261,64.126111,47.500000,2.098653,2.181650,2.913538,2.472681,1.979007,3.945079,5.793661,6.629026,4.664032,5.168485,4.154190,3,1
10-261,10,261,80.000000,5.500000,2.098653,2.181650,2.913538,2.472681,1.979007,3.945079,5.793661,6.629026,4.664032,5.168485,4.154190,4,2
10-261,10,261,276.683333,0.000000,2.098653,2.181650,2.913538,2.472681,1.979007,3.945079,5.793661,6.629026,4.664032,5.168485,4.154190,5,3
10-262,10,262,43.196816,51.973483,0.899423,0.934993,1.248659,1.059720,0.848146,1.690748,2.482998,2.841011,1.998871,2.215065,1.780367,1,1
10-262,10,262,57.423485,52.500000,0.899423,0.934993,1.248659,1.059720,0.848146,1.690748,2.482998,2.841011,1.998871,2.215065,1.780367,2,1
10-262,10,262,21.700000,50.500000,0.899423,0.934993,1.248659,1.059720,0.848146,1.690748,2.482998,2.841011,1.998871,2.215065,1.780367,3,1
10-262,10,262,75.000000,8.250000,0.899423,0.934993,1.248659,1.059720,0.848146,1.690748,2.482998,2.841011,1.998871,2.215065,1.780367,4,2
10-262,10,262,362.700000,0.000000,0.899423,0.934993,1.248659,1.059720,0.848146,1.690748,2.482998,2.841011,1.998871,2.215065,1.780367,5,3
10-263,10,263,44.999064,51.737079,0.799487,0.831105,1.109919,0.941974,0.753907,1.502887,2.207109,2.525343,1.776774,1.968946,1.582548,1,1
10-263,10,263,49.215054,52.500000,0.799487,0.831105,1.109919,0.941974,0.753907,1.502887,2.207109,2.525343,1.776774,1.968946,1.582548,2,1
10-263,10,263,51.792857,51.000000,0.799487,0.831105,1.109919,0.941974,0.753907,1.502887,2.207109,2.525343,1.776774,1.968946,1.582548,3,1
10-263,10,263,67.000000,8.250000,0.799487,0.831105,1.109919,0.941974,0.753907,1.502887,2.207109,2.525343,1.776774,1.968946,1.582548,4,2
10-263,10,263,331.900000,0.000000,0.799487,0.831105,1.109919,0.941974,0.753907,1.502887,2.207109,2.525343,1.776774,1.968946,1.582548,5,3

## Modeling

### Nested Logit Model

In [7]:
def utility(mode, wage, Lambda, dataset):
    '''
    Get the utility for mode j under specific OD pair
    Lambda: parameter that trade-off different transportation mode
    '''
    subset = dataset[dataset['mode'] == mode]
    vj = Lambda * (float(int(wage)/124800) * float(subset['duration']) + float(subset['price'])) #525600: convert wage scale 'year' to 'minitues'
    return -vj #assign negative utility?


def InclusiveValue(Nk, Tk, wage, dictVj, Lambda, dataset):
    '''
    Get the inclusive value for nest K
    Nk:nest k
    T: the dict that contains Tao(dissmilarity parameter) for each Nest. for example, Tk meeas Tao for nest K
    '''
    subsetNk = dataset[dataset['nest'] == Nk]
    modes = list(subsetNk['mode'].unique()) #what modes contained in this nest k
    sumIV = 0
    for j in modes:   
        vj = utility(j, wage, Lambda, subsetNk)
        dictVj[j] = vj
        sumIV += np.exp((1/Tk)*vj)  
    IVk = np.log(sumIV)
    return dictVj, IVk
    

def denoSum(T, nestList, wage, Lambda, dataset):
    '''
    Calculate the denomenator for P(y=Nk)
    T: the dict that contains Tk for each Nest, in our case T={1:T1, 2:T2, 3:T3}; T1, T2, T3 defined by us 
    TotK: the total number of nest this model has, in our case TotK = 3
    '''
    deno = 0
    dictIVk = {}
    dictVj = {}
    for Nk in nestList: #k is the k Nest, in our case k=1,2,3
        Tk = T[Nk] #get the tao for nest k 
        dictVj, IVk = InclusiveValue(Nk, Tk, wage, dictVj, Lambda, dataset)
        denok = np.exp(Tk*IVk)
        deno += denok
        dictIVk[Nk] = IVk
    return dictVj, dictIVk, deno


def probability (j, Nk, T, dictVj, dictIVk, deno):  
    '''
    Calculate the probability for the specific mode j and Nest Nk
    '''
    Tk = T[Nk]
    IVk = dictIVk[Nk]
    vj = dictVj[j]
    pjk = np.exp((1/Tk)*vj)/np.exp(IVk) #pjk: P(y=j, y belong to Nk)
    pk = np.exp(Tk*IVk)/deno #pk: P(y belong to Nk)
    pj = pjk*pk #pj: P(y=j)
    return pj

### Apply to our case

In [15]:
def apply_model(T, nestList, wageList, Lambda, dataAll):
    '''
    apply to our case
    '''
    import timeit
    start = timeit.default_timer()

    ODpair_list = list(dataAll.index.unique())
    p = []
    for i in tqdm(ODpair_list,position=0): #indentify OD pair  
        dataOD = dataAll[dataAll.index==i] 
        modeList = list(dataOD['mode'])
        nestList = list(dataOD['nest'])
        
        pop_OD = [] #store the results under each OD pair
        for wage in wageList:            
            dictVj, dictIVk, deno = denoSum(T, set(nestList), wage, Lambda, dataOD)
            pop_mode = [] #store the results under each OD pair and each wage
            for i in range(1,6):
                if i in modeList: #not all modes appear in every OD pair
                    pop = dataOD[wage].mean() * probability(i, nestList[modeList.index(i)], T, dictVj, dictIVk, deno)
#                     print(wage, i,nestList[modeList.index(i)], pop)
                    if np.isnan(pop) == True: #if predicted population is nan, replace it as 0, means no people choose
                        pop = 0
                
                    pop_mode.append(pop)
                else: 
                    pop_mode.append(0)
            pop_OD.append(pop_mode)
        pop_OD_sum = [sum(x) for x in zip(*pop_OD)] #sum the weighted population under each wage scenario
        p.append(pop_OD_sum)

    df = pd.DataFrame(p, columns=['P(mode1)', 'P(mode2)', 'P(mode3)', 'P(mode4)', 'P(mode5)']
                      , index=ODpair_list)
    
    stop = timeit.default_timer()
    timeslot = stop - start
    return df, timeslot

def compare_with_ground_truth(predictdf, truedf):
    '''
    compare our predicted transportation choice with ground truth
    
    The header of the datafrme after merge (named 'data_compare') should be like:
    taxi_zone | P(mode1)_x | P(mode2)_x | P(mode3)_x | P(mode4)_x | P(mode5)_x | P(mode1)_y | P(mode2)_y | P(mode3)_y | P(mode4)_y | P(mode5)_y
    '''
    import numpy as np
    # makesure predictdf and truedf have the same formats
    for col in predictdf.columns:
        predictdf[col] = predictdf[col].astype(float) 
    predictdf = predictdf.fillna(0)
    predictdf = predictdf.replace([np.inf, -np.inf], np.nan)
    predictdf = predictdf.dropna()
    predictdf['taxi_zone'] = predictdf.index.map(lambda x: x.split('-')[0]) #get origin taxi zone from each OD pair
    predictdf = predictdf.groupby('taxi_zone').sum().reset_index() #group the popuation by taxi zone
    predictdf['taxi_zone'] = predictdf['taxi_zone'].astype(int)
    truedf['taxi_zone'] = truedf['taxi_zone'].astype(int)
    
    data_compare = pd.merge(predictdf, truedf, left_on='taxi_zone', right_on = 'taxi_zone', how = 'left')
    data_compare = data_compare.dropna() 
    
    rmse = 0
    for i in range(1,6):
        rmsei = np.sqrt(sum((data_compare[data_compare.columns[i]] - data_compare[data_compare.columns[i+5]])**2))
    rmse += rmsei
    return data_compare, rmse

In [16]:
#choose ODpair 3-1 to test the algrithm whether bug-free:
T1 = 10
T2 = 1
T3 = 1
T = {1:T1, 2:T2, 3:T3} #Tao for each nest
Lambda = 2 
nestList = [1, 2, 3]
wagelist = ['2500', '7500', '12500', '17500', '22500', '30000', '42500', '62500', '87500', '125000', '225000']
testdf = mode_data[mode_data.index.isin(list(mode_data.index[:10]))] #test OD pair 3-1,3-2,3-3,3-4

predict_choice_test, timeslot_test = apply_model(T, nestList, wagelist, Lambda, testdf)
results_test,rmse_test = compare_with_ground_truth(predict_choice_test, acs)
print('The time used to run the code:', timeslot_test)
print('The rmse of this model is:', rmse_test)
print()
print('The predict transportation choice is:')
predict_choice_test

100%|██████████| 3/3 [00:00<00:00, 27.96it/s]

The time used to run the code: 0.11084773900074651
The rmse of this model is: 913.7195608142687

The predict transportation choice is:

       P(mode1)  P(mode2)  P(mode3)   P(mode4)  P(mode5)
3-3  273.000000  0.000000  0.000000   0.000000  0.000000
3-4    0.000000  0.419544  0.094461   5.235710  0.250285
3-7    0.032738  3.028392  0.496368  30.953772  1.488730

In [13]:
combine_test

NameError: name 'combine_test' is not defined

In [35]:
#Run the model for the whole dataset
T1 = 0.5455594781168515 #should set grid search for T1 
T2 = 1
T3 = 1
T = {1:T1, 2:T2, 3:T3} #Tao for each nest
Lambda = 0.04832930238571752 #should set grid search for Lambda 
nestList = [1, 2, 3]
wagelist = ['2500', '7500', '12500', '17500', '22500', '30000', '42500', '62500', '87500', '125000', '225000']

predict_transportation_choice, timeslot = apply_model(T, nestList, wagelist, Lambda, mode_data[:7242])
results,rmse = compare_with_ground_truth(predict_transportation_choice, acs[:7])

100%|██████████| 1742/1742 [01:16<00:00, 22.69it/s]

In [36]:
rmse

1984.397455871008

In [37]:
#Run the model for the whole dataset
T1 = 0.5 #should set grid search for T1 
T2 = 1
T3 = 1
T = {1:T1, 2:T2, 3:T3} #Tao for each nest
Lambda = 22 #should set grid search for Lambda 
nestList = [1, 2, 3]
wagelist = ['2500', '7500', '12500', '17500', '22500', '30000', '42500', '62500', '87500', '125000', '225000']

predict_transportation_choice, timeslot = apply_model(T, nestList, wagelist, Lambda, mode_data[:7242])
results,rmse = compare_with_ground_truth(predict_transportation_choice, acs[:7])

100%|██████████| 1742/1742 [01:11<00:00, 22.73it/s]

In [38]:
rmse

2058.6316307001193

In [ ]:
#Run the model for the whole dataset
T1 = 3000 #should set grid search for T1 
T2 = 1
T3 = 1
T = {1:T1, 2:T2, 3:T3} #Tao for each nest
Lambda = 2 #should set grid search for Lambda 
nestList = [1, 2, 3]
wagelist = ['2500', '7500', '12500', '17500', '22500', '30000', '42500', '62500', '87500', '125000', '225000']

predict_transportation_choice, timeslot = apply_model(T, nestList, wagelist, Lambda, mode_data)
combine, rmse = compare_with_ground_truth(predict_transportation_choice, acs)

In [9]:
print('The time used to run the code:', timeslot)
print('The mse of this model is:', mse)
print()
print('The predict transportation choice is:')
predict_transportation_choice

The time used to run the code: 3545.58184884
The mse of this model is: 4004786.8137141904

The predict transportation choice is:

             P(mode1)      P(mode2)     P(mode3)     P(mode4)      P(mode5)
3-1        561.083498  5.583506e+02   501.565913     0.000000  0.000000e+00
3-2          0.000000  0.000000e+00     0.000000  6170.000000  1.164735e-43
3-3      18922.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
3-4          0.000000  8.481136e+02   772.886437     0.000000  0.000000e+00
3-5          0.000000  0.000000e+00     0.000000  4862.000000  1.407611e-83
3-6          0.000000  6.181992e+03     0.000000  3972.008201  2.108063e-54
3-7          0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
3-8          0.000000  0.000000e+00     0.000000  8037.000000  1.894266e-28
3-9          0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
3-10         0.000000  2.475536e+03  1481.464104     0.000000  0.000000e+00
3-11         0.000000  4.329315e-56     0.000000  8037.000000  3.283106e-45
3-12         0.000000  1.214040e+03  1121.960163     0.000000  0.000000e+00
3-13         0.000000  1.772954e+03  2184.045862     0.000000  0.000000e+00
3-14         0.000000  2.276631e+03  1910.368910     0.000000  0.000000e+00
3-15         0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
3-16         0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
3-17         0.000000  1.225014e+03  1110.985982     0.000000  0.000000e+00
3-18         0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
3-19         0.000000  8.326586e+02   788.341371     0.000000  0.000000e+00
3-20         0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
3-21         0.000000  2.259600e+03  1927.400099     0.000000  0.000000e+00
3-22         0.000000  4.065000e+03     0.000000  3971.999798  1.086562e-40
3-23         0.000000  2.146338e+03  2040.662103     0.000000  0.000000e+00
3-24         0.000000  8.378408e+02   783.159159     0.000000  0.000000e+00
3-25       363.525566  5.955457e+02   661.928700     0.000000  0.000000e+00
3-26       365.043468  8.173668e+02   438.589714     0.000000  0.000000e+00
3-27         0.000000  0.000000e+00     0.000000     0.000000  1.927000e+03
3-28         0.000000  6.739546e+02   947.045356     0.000000  0.000000e+00
3-29         0.000000  4.064958e+03     0.000000  3972.042099  9.593175e-60
3-30         0.000000  2.123735e+03  1833.265112     0.000000  0.000000e+00
...               ...           ...          ...          ...           ...
263-236      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-237      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-238      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-239      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-240      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-241      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-242      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-243      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-244      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-245      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-246      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-247      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-248      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-249      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-250      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-251   9434.268331  7.402732e+03     0.000000     0.000000  0.000000e+00
263-252      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-253      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-254      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-255      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-256      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-257      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-258      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-259      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-260      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-261      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-262      0.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-263  33964.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-264  33964.000000  0.000000e+00     0.000000     0.000000  0.000000e+00
263-265  12872.000000  0.000000e+00     0.000000     0.000000  0.000000e+00

[67398 rows x 5 columns]